#! /usr/local/bin/perl

# Usage: csmap_to_pgm < csmap.ascii.mmddyy.hhss > file.pgm
#
# To view the resulting image, use:
#  xv -hist -expand 4 -raw -vflip file.pgm

printf("P2\n");
printf("# csmap image.\n");
printf("151 151\n");
printf("99\n");
while(<>) {
	s/-//g;
	print;
}
